name: Clang Tidy Review
on: [pull_request]
permissions:
  pull-requests: write
jobs:
  clang-tidy:
    name: Clang Tidy Review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ZedThree/clang-tidy-review@v0.10.1
      id: review
      with:
        cmake_command: 'cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=on'
        build_dir: 'build'
        config_file: '.clang-tidy'
        exclude: 'chuffed/vars/int-var-*.h,thirdparty/**'
        apt_packages: 'zlib1g-dev'
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
